### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by andre-brdoch** [andre-brdoch/swedish-tool#1]
MVP 1
- [x] minmal app: type in verb, display all inflections
- [x] build & host

Finish tooling setup
- [x] set up linting 
- [x] set up prettier
- [x] set up stylelint
- [x] validate in CI

v2
- [x] extract inflections from payload

v3
- [ ] add api integration
- [ ] proper ui
